apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testdj-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: testdj.codeeper.com
    http:
      paths:
      - path: /
        backend:
          serviceName: testdj-svc
          servicePort: 8000
